apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

resources:
- addons
- oauth2-proxy
- certificates.yaml
## enable mTLS for the whole mesh
#- peerauthentication-default.yaml
# authenticate enduser at ingressgateway using oauth2-proxy
- authorizationpolicy-enduser.yaml
