apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: not-used
    spec:
      template:
        metadata:
          labels:
            istio-addon: "true"
            sidecar.istio.io/inject: "true"
  target:
    group: apps
    version: v1
    kind: Deployment

resources:
- https://raw.githubusercontent.com/istio/istio/1.13.0/samples/addons/grafana.yaml
- https://raw.githubusercontent.com/istio/istio/1.13.0/samples/addons/jaeger.yaml
- https://raw.githubusercontent.com/istio/istio/1.13.0/samples/addons/kiali.yaml
- https://raw.githubusercontent.com/istio/istio/1.13.0/samples/addons/prometheus.yaml
- addons-gateway.yaml
- virtualservice-grafana.yaml
- virtualservice-kiali.yaml
- virtualservice-prometheus.yaml
- virtualservice-tracing.yaml
# allow kiali and grafana to talk to prometheus
- authorizationpolicy-peers.yaml
# require valid JWT for addons
- requestauthentication-addons.yaml
# restrict addon access to timebertt
- authorizationpolicy-enduser.yaml
