apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookinfo

resources:
- ../base
- https://raw.githubusercontent.com/istio/istio/release-1.13/samples/bookinfo/networking/virtual-service-reviews-test-v2.yaml
- https://raw.githubusercontent.com/istio/istio/release-1.13/samples/bookinfo/networking/virtual-service-ratings-test-delay.yaml

replicas:
- name: reviews-v2
  count: 1
- name: reviews-v3
  count: 0
- name: ratings-v1
  count: 1
